<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_guest_arrival_tests.TestHotelReservation-20240420190931" tests="3" file="test_guest_arrival_tests.py" time="0.124" timestamp="2024-04-20T19:09:32" failures="0" errors="1" skipped="0">
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_case_valid_reservation_invalid_arrival_date" time="0.004" timestamp="2024-04-20T19:09:32"/>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_get_reservation_data_manipulated_tests" time="0.004" timestamp="2024-04-20T19:09:32"/>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 1VALID]" time="0.115" timestamp="2024-04-20T19:09:32">
		<error type="TypeError" message="__init__() got an unexpected keyword argument 'numdays'"><![CDATA[Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 499, in subTest
    yield
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 102, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 151, in guest_arrival
    my_checkin = HotelStay(idcard=my_id_card, numdays=int(reservation_days),
TypeError: __init__() got an unexpected keyword argument 'numdays'
]]></error>
	</testcase>
</testsuite>
