<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest.loader._FailedTest-20240419155312" tests="3" file="unittest/loader.py" time="0.004" timestamp="2024-04-19T15:53:12" failures="0" errors="3" skipped="0">
	<testcase classname="unittest.loader._FailedTest" name="test_checkout_tests" time="0.003" timestamp="2024-04-19T15:53:12">
		<error type="ImportError" message="Failed to import test module: test_checkout_tests
Traceback (most recent call last):
  File &quot;/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_checkout_tests.py&quot;, line 7, in &lt;module&gt;
    from uc3m_travel import HotelManager
  File &quot;/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/__init__.py&quot;, line 3, in &lt;module&gt;
    from .hotel_manager import HotelManager
  File &quot;/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py&quot;, line 21, in &lt;module&gt;
    from storage.reservation_json_store import ReservationJsonStore
  File &quot;/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/storage/reservation_json_store.py&quot;, line 2, in &lt;module&gt;
    from uc3m_travel import JSON_FILES_PATH
ImportError: cannot import name 'JSON_FILES_PATH' from partially initialized module 'uc3m_travel' (most likely due to a circular import) (/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/__init__.py)
"><![CDATA[Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_checkout_tests
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_checkout_tests.py", line 7, in <module>
    from uc3m_travel import HotelManager
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/__init__.py", line 3, in <module>
    from .hotel_manager import HotelManager
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 21, in <module>
    from storage.reservation_json_store import ReservationJsonStore
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/storage/reservation_json_store.py", line 2, in <module>
    from uc3m_travel import JSON_FILES_PATH
ImportError: cannot import name 'JSON_FILES_PATH' from partially initialized module 'uc3m_travel' (most likely due to a circular import) (/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/__init__.py)

]]></error>
	</testcase>
	<testcase classname="unittest.loader._FailedTest" name="test_guest_arrival_tests" time="0.001" timestamp="2024-04-19T15:53:12">
		<error type="ImportError" message="Failed to import test module: test_guest_arrival_tests
Traceback (most recent call last):
  File &quot;/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py&quot;, line 10, in &lt;module&gt;
    from uc3m_travel import (JSON_FILES_PATH,
  File &quot;/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/__init__.py&quot;, line 3, in &lt;module&gt;
    from .hotel_manager import HotelManager
  File &quot;/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py&quot;, line 21, in &lt;module&gt;
    from storage.reservation_json_store import ReservationJsonStore
  File &quot;/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/storage/reservation_json_store.py&quot;, line 2, in &lt;module&gt;
    from uc3m_travel import JSON_FILES_PATH
ImportError: cannot import name 'JSON_FILES_PATH' from partially initialized module 'uc3m_travel' (most likely due to a circular import) (/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/__init__.py)
"><![CDATA[Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_guest_arrival_tests
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 10, in <module>
    from uc3m_travel import (JSON_FILES_PATH,
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/__init__.py", line 3, in <module>
    from .hotel_manager import HotelManager
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 21, in <module>
    from storage.reservation_json_store import ReservationJsonStore
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/storage/reservation_json_store.py", line 2, in <module>
    from uc3m_travel import JSON_FILES_PATH
ImportError: cannot import name 'JSON_FILES_PATH' from partially initialized module 'uc3m_travel' (most likely due to a circular import) (/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/__init__.py)

]]></error>
	</testcase>
	<testcase classname="unittest.loader._FailedTest" name="test_room_reservation_tests" time="0.001" timestamp="2024-04-19T15:53:12">
		<error type="ImportError" message="Failed to import test module: test_room_reservation_tests
Traceback (most recent call last):
  File &quot;/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py&quot;, line 9, in &lt;module&gt;
    from uc3m_travel import (JSON_FILES_PATH,
  File &quot;/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/__init__.py&quot;, line 3, in &lt;module&gt;
    from .hotel_manager import HotelManager
  File &quot;/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py&quot;, line 21, in &lt;module&gt;
    from storage.reservation_json_store import ReservationJsonStore
  File &quot;/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/storage/reservation_json_store.py&quot;, line 2, in &lt;module&gt;
    from uc3m_travel import JSON_FILES_PATH
ImportError: cannot import name 'JSON_FILES_PATH' from partially initialized module 'uc3m_travel' (most likely due to a circular import) (/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/__init__.py)
"><![CDATA[Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_room_reservation_tests
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 9, in <module>
    from uc3m_travel import (JSON_FILES_PATH,
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/__init__.py", line 3, in <module>
    from .hotel_manager import HotelManager
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 21, in <module>
    from storage.reservation_json_store import ReservationJsonStore
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/storage/reservation_json_store.py", line 2, in <module>
    from uc3m_travel import JSON_FILES_PATH
ImportError: cannot import name 'JSON_FILES_PATH' from partially initialized module 'uc3m_travel' (most likely due to a circular import) (/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/__init__.py)

]]></error>
	</testcase>
</testsuite>
